-- Punho multiempresa. Executar no schema public, após auth estar disponível.
create extension if not exists pgcrypto;
create table if not exists punho_empresas (id uuid primary key default gen_random_uuid(), nome text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), revision int not null default 1);
create table if not exists punho_membros (id uuid primary key default gen_random_uuid(), empresa_id uuid not null references punho_empresas(id), user_id uuid not null references auth.users(id), perfil text not null check(perfil in ('gestor','colaborador')), ativo boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(empresa_id,user_id));
create or replace function punho_empresa_atual() returns uuid language sql security definer stable set search_path=public as $$ select empresa_id from punho_membros where user_id=auth.uid() and ativo limit 1 $$;
create or replace function punho_e_gestor() returns boolean language sql security definer stable set search_path=public as $$ select exists(select 1 from punho_membros where user_id=auth.uid() and ativo and perfil='gestor') $$;
create table if not exists punho_clientes (id uuid primary key default gen_random_uuid(), empresa_id uuid not null references punho_empresas(id), nome text not null, telemovel text, nif text, created_by uuid references auth.users(id), updated_at timestamptz not null default now(), created_at timestamptz not null default now(), revision int not null default 1, unique(empresa_id,telemovel), unique(empresa_id,nif));
create table if not exists punho_reservas (id uuid primary key default gen_random_uuid(), empresa_id uuid not null references punho_empresas(id), cliente_id uuid not null references punho_clientes(id), colaborador_responsavel_id uuid references punho_membros(id), cliente_nome_snapshot text not null, colaborador_nome_snapshot text, inicio timestamptz not null, fim timestamptz not null, estado text not null, valor_previsto_centimos int, created_by uuid references auth.users(id), updated_at timestamptz not null default now(), created_at timestamptz not null default now(), revision int not null default 1);
create table if not exists punho_reserva_maquinas (reserva_id uuid references punho_reservas(id) on delete cascade, maquina_id uuid not null, primary key(reserva_id,maquina_id));
do $$ declare t text; begin foreach t in array array['punho_leads','punho_colaboradores','punho_maquinas','punho_veiculos','punho_recebimentos','punho_despesas','punho_documentos','punho_campanhas','punho_eventos_auditoria','punho_instalacoes','punho_subscricoes'] loop execute format('create table if not exists %I (id uuid primary key default gen_random_uuid(), empresa_id uuid not null references punho_empresas(id), created_by uuid references auth.users(id), updated_at timestamptz not null default now(), created_at timestamptz not null default now(), revision int not null default 1, dados jsonb not null default ''{}''::jsonb)',t); end loop; end $$;
alter table punho_subscricoes add column if not exists limite_colaboradores_ativos int not null default 3;
-- Reserva confirmada/em aluguer não pode sobrepor mesma máquina.
create or replace function punho_validar_conflito_reserva() returns trigger language plpgsql security definer set search_path=public as $$ begin if exists(select 1 from punho_reservas r join punho_reserva_maquinas rm on rm.reserva_id=r.id where rm.maquina_id=new.maquina_id and r.id<>new.reserva_id and r.estado in ('confirmada','em_aluguer') and exists(select 1 from punho_reservas n where n.id=new.reserva_id and n.estado in ('confirmada','em_aluguer') and n.inicio<r.fim and n.fim>r.inicio)) then raise exception 'Conflito de reserva para máquina %',new.maquina_id using errcode='23P01'; end if; return new; end $$;
drop trigger if exists punho_reserva_conflict on punho_reserva_maquinas; create trigger punho_reserva_conflict before insert or update on punho_reserva_maquinas for each row execute function punho_validar_conflito_reserva();
do $$ declare t text; begin foreach t in array array['punho_empresas','punho_membros','punho_clientes','punho_leads','punho_colaboradores','punho_maquinas','punho_veiculos','punho_reservas','punho_reserva_maquinas','punho_recebimentos','punho_despesas','punho_documentos','punho_campanhas','punho_eventos_auditoria','punho_instalacoes','punho_subscricoes'] loop execute format('alter table %I enable row level security',t); end loop; end $$;
-- Aplicar políticas por empresa; despesas/subscrições/auditoria ficam apenas para gestor.
create policy "membros empresa" on punho_clientes for all using (empresa_id=punho_empresa_atual()) with check (empresa_id=punho_empresa_atual());
create policy "reservas empresa" on punho_reservas for all using (empresa_id=punho_empresa_atual()) with check (empresa_id=punho_empresa_atual());
create policy "gestor despesas" on punho_despesas for all using (empresa_id=punho_empresa_atual() and punho_e_gestor()) with check (empresa_id=punho_empresa_atual() and punho_e_gestor());
create policy "gestor subscricao" on punho_subscricoes for all using (empresa_id=punho_empresa_atual() and punho_e_gestor()) with check (empresa_id=punho_empresa_atual() and punho_e_gestor());
